# Generated by Django 4.2.8 on 2023-12-28 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Действие')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('location', models.CharField(max_length=50, verbose_name='Место')),
                ('is_nice', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodic', models.CharField(blank=True, choices=[(1, '1 День'), (2, '2 Дня'), (3, '3 Дня'), (4, '4 Дня'), (5, '5 Дней'), (6, '6 Дней'), (7, '7 Дней')], default=1, max_length=2, null=True, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(default=120, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_habits.habit', verbose_name='Привязка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
