# Generated by Django 4.2.8 on 2024-01-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_habits', '0004_alter_habit_periodic'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата начала'),
        ),
    ]
