# Generated by Django 4.2.9 on 2024-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_habits', '0007_remove_habit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodic',
            field=models.PositiveIntegerField(blank=True, choices=[('1', '1 День'), ('2', '2 Дня'), ('3', '3 Дня'), ('4', '4 Дня'), ('5', '5 Дней'), ('6', '6 Дней'), ('7', '7 Дней')], default='1', null=True, verbose_name='Периодичность'),
        ),
    ]
